# Generated by Django 4.1.7 on 2023-03-22 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_dado_id_comprador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creditos', to='home.pessoas'),
        ),
        migrations.AlterField(
            model_name='debito',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='debitos', to='home.pessoas'),
        ),
        migrations.AlterField(
            model_name='repasseretido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='repasses_retidos', to='home.pessoas'),
        ),
        migrations.AlterField(
            model_name='taxa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='taxas', to='home.pessoas'),
        ),
    ]
