# Generated by Django 4.1.7 on 2023-03-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_credito_cliente_alter_debito_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='pago',
            field=models.BooleanField(blank=True, null=True, verbose_name='Esse campo serve para distinguir quais dados foram pagos'),
        ),
    ]
