# Generated by Django 4.1.3 on 2023-03-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_repasseaprovado_id_vendedor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repasseaprovado',
            name='dado',
        ),
        migrations.AddField(
            model_name='repasseaprovado',
            name='dado',
            field=models.ManyToManyField(blank=True, null=True, to='home.dado'),
        ),
    ]
