# Generated by Django 4.1.3 on 2023-03-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_repasseaprovado_dado_repasseaprovado_dado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repasseaprovado',
            name='dado',
            field=models.ManyToManyField(blank=True, to='home.dado'),
        ),
    ]
