# Generated by Django 4.1.3 on 2023-04-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_pessoas_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelataxa',
            name='data_criado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='parcelataxa',
            name='id_comprador',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='parcelataxa',
            name='id_vendedor',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='repasseaprovado',
            name='data_aprovado',
            field=models.DateTimeField(blank=True, null=True, verbose_name=''),
        ),
    ]
