# Generated by Django 4.1.3 on 2023-04-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_credito_aprovada_debito_aprovada_taxa_aprovada'),
    ]

    operations = [
        migrations.AddField(
            model_name='repasseretido',
            name='aprovada',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name=''),
        ),
    ]
