# Generated by Django 3.2.16 on 2023-05-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_rename_data_criado_parcelataxa_criado'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='aprovada_para_repasse',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='dado',
            name='aprovada_para_repasse',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='debito',
            name='aprovada_para_repasse',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='parcelataxa',
            name='aprovada_para_repasse',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='taxa',
            name='aprovada_para_repasse',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='repasseretido',
            name='aprovada',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='O campo aprovada é utilizado para saber se sera computado para a tabela repasses ou não'),
        ),
    ]
