# Generated by Django 3.2.16 on 2023-05-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20230510_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='repasseretido',
            name='aprovada_para_repasse',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name=''),
        ),
    ]
