# Generated by Django 3.2.16 on 2023-05-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20230510_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repasseaprovado',
            old_name='dados',
            new_name='repasses',
        ),
        migrations.RemoveField(
            model_name='repasseaprovado',
            name='total_credito',
        ),
        migrations.RemoveField(
            model_name='repasseaprovado',
            name='total_debito',
        ),
        migrations.RemoveField(
            model_name='repasseaprovado',
            name='total_repasse',
        ),
        migrations.RemoveField(
            model_name='repasseaprovado',
            name='total_repasses_retidos',
        ),
        migrations.RemoveField(
            model_name='repasseaprovado',
            name='total_taxa',
        ),
        migrations.AddField(
            model_name='repasseaprovado',
            name='creditos',
            field=models.ManyToManyField(to='home.Credito', verbose_name='creditos'),
        ),
        migrations.AddField(
            model_name='repasseaprovado',
            name='debitos',
            field=models.ManyToManyField(to='home.Debito', verbose_name='debitos'),
        ),
        migrations.AddField(
            model_name='repasseaprovado',
            name='repasses_retidos',
            field=models.ManyToManyField(to='home.RepasseRetido', verbose_name='repasses_retidos'),
        ),
        migrations.AddField(
            model_name='repasseaprovado',
            name='taxas',
            field=models.ManyToManyField(to='home.Taxa', verbose_name='taxas'),
        ),
    ]
