# Generated by Django 3.2.16 on 2023-05-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20230510_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='repasseaprovado',
            name='parcelas_taxas',
            field=models.ManyToManyField(to='home.ParcelaTaxa', verbose_name='parcelas_taxas'),
        ),
        migrations.AlterField(
            model_name='repasseaprovado',
            name='data_aprovado',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=''),
        ),
    ]
