# Generated by Django 3.2.16 on 2023-05-18 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_pessoas_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadcliente',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='home.pessoas'),
        ),
    ]
