# Generated by Django 4.2.3 on 2023-07-30 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_parcelataxa_data_aprovada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repasseaprovado',
            name='data_aprovado',
            field=models.DateField(auto_now_add=True, null=True, verbose_name=''),
        ),
    ]
