# Generated by Django 4.2.3 on 2023-09-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_repasseaprovado_data_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='vendedores',
            field=models.ManyToManyField(blank=True, related_name='contratos_como_vendedores', to='home.pessoas'),
        ),
    ]
