# Generated by Django 4.2.3 on 2023-09-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_contratos_vendedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoparcelas',
            name='aprovada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contratoparcelas',
            name='aprovada_para_repasse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='pessoas_id_inclusao',
            field=models.ForeignKey(blank=True, db_column='pessoas_id_inclusao', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.pessoas'),
        ),
    ]
