# Generated by Django 4.2.3 on 2023-09-05 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_contratoparcelas_aprovada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='vendedores',
        ),
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contratos', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pesos', to='home.contratos')),
                ('pessoa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.pessoas')),
            ],
            options={
                'verbose_name': 'Peso',
                'verbose_name_plural': 'Pesos',
                'db_table': 'pesos',
                'managed': True,
            },
        ),
    ]
