# Generated by Django 4.2.3 on 2023-09-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_contratos_eventos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peso',
            old_name='contratos',
            new_name='contrato',
        ),
    ]
