# Generated by Django 4.2.3 on 2023-09-06 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_rename_contratos_peso_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peso',
            name='contrato',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesos', to='home.contratos'),
        ),
    ]
