# Generated by Django 4.2.3 on 2023-09-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_peso_adi_peso_me_peso_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoparcelas',
            name='data_aprovada',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
