# Generated by Django 4.2.3 on 2023-09-11 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_contratoparcelas_data_aprovada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peso',
            name='parcela',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesos', to='home.contratoparcelas'),
        ),
    ]
