# Generated by Django 4.2.3 on 2023-09-11 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_alter_peso_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoparcelas',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='contratoparcelas',
            name='rateio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='contratoparcelas',
            name='vl_repasse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='peso',
            name='parcela',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peso', to='home.contratoparcelas'),
        ),
    ]
