# Generated by Django 4.2.3 on 2023-09-12 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_contratoparcelas_comissao_contratoparcelas_rateio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadcliente',
            name='vendedor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='home.pessoas'),
        ),
        migrations.AlterField(
            model_name='contratoparcelas',
            name='data_aprovada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
