# Generated by Django 4.2.3 on 2023-09-12 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_peso_adi_alter_peso_me_alter_peso_op_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peso',
            name='pessoa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.pessoas'),
        ),
    ]
