# Generated by Django 4.2.3 on 2023-09-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_contratoparcelas_eh_adi'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelataxa',
            name='deletada',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name=''),
        ),
    ]
