# Generated by Django 4.2.3 on 2023-09-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_parcelataxa_deletada'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxa',
            name='data_aprovada',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
    ]
