# Generated by Django 4.2.3 on 2023-10-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_taxa_data_aprovada'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxa',
            name='criada_em',
            field=models.DateField(auto_now_add=True, null=True, verbose_name=''),
        ),
    ]
