# Generated by Django 4.2.3 on 2023-10-18 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0060_taxa_criada_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoparcelas',
            name='comissionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
