# Generated by Django 4.2.3 on 2023-10-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_contratoparcelas_comissionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoparcelas',
            name='id_original',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
