# Generated by Django 3.2.16 on 2023-05-15 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao', models.CharField(blank=True, choices=[('consulta', 'consulta'), ('alimentacao', 'alimentacao')], max_length=32, null=True, verbose_name='Esse campo serve para identificar as permissões de cada usuario')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acesso', to=settings.AUTH_USER_MODEL, verbose_name='Esse campo serve para identificar os acessos e permissões de cada usuario')),
            ],
            options={
                'verbose_name': 'acesso',
                'verbose_name_plural': 'acessos',
                'db_table': 'acessos',
                'ordering': ['user'],
                'managed': True,
            },
        ),
    ]
